name: CI Pipeline 

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - name: Kodu Çek
        uses: actions/checkout@v3 

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3 
        with:
          node-version: '14'

      - name: Testleri Çalıştır
        run: npm test  
